name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build docker image
      run: docker build -t samitizer .
    - name: test with docker
      run: docker run samitizer
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: apt install
      run: sudo apt-get install uchardet
    - name: prepare python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: pip install
      run: |
        python -m pip install --upgrade pip
        pip install nose nose-exclude flake8 coverage coveralls
    - name: test with nose
      run: nosetests --config=.noserc
    - name: lint with flake
      run: flake8
    - name: send to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_token }}
      run: coveralls
