name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: prepare python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: pip install
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: build package
      run: python setup.py sdist bdist_wheel
    - name: upload with twine
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
      run: twine upload dist/*
