name: test

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: docker build -t samitizer -f Dockerfile .
    - name: test
      run: docker run samitizer
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
