name: test

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: docker build -t samitizer -f Dockerfile .
    - name: test
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_token }}
      run: docker run -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" samitizer bash -c 'nosetests --config=.noserc && coveralls'
